---
- name: Deploying cloud formation template via ansbile stack
  cloudformation:
    stack_name: "{{ stack_prefix }}-{{ env }}-{{ branch }}"
    state: present
    region: us-east-1
    disable_rollback: false
    template_url: https://s3.amazonaws.com/{{ bucketname }}/{{ subdirectory }}/EMR-self-terminating_NONPROD_{{ branch }}.yaml
    template_parameters: "{{ lookup('file', 'parameters/{{ branch }}_parameters.json') | from_json }}"
    tags:
      Name: "{{ stack_prefix }}-{{ env }}-{{ branch }}"