---

- name: "Delete temporary files - pre"
  file:
    path: ./tmp/{{ item | basename }}
    state: absent
  with_fileglob: 
   - cf_templates/*

- name: "Prepare Cloudformation templates"
  template:
    src: "{{ item }}"
    dest: ./tmp/{{ item | basename }}
    mode: 0644
  with_fileglob: 
   - cf_templates/*


- name: "upload Cloudformation templates to s3"
  aws_s3:
    bucket: "{{ bucketname }}"
    object: "{{ subdirectory }}/{{ item | basename }}"
    src: ./tmp/{{ item | basename }}
    encrypt: yes
    encryption_mode: AES256
    overwrite: always
    mode: put
  with_fileglob: 
   - cf_templates/*

# - name: "Delete temporary files - post"
#   file:
#     path: ./tmp/{{ item | basename | replace('.j2', '') }}
#     state: absent
#   with_fileglob: 
#    - cf_templates/*.j2
